In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [3]:
# loading dataset
data = pd.read_csv("/content/Churn_Modelling.csv")

# checking data
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# checking dataset size
print(data.shape)

# checking columns
print(data.columns)

(10000, 14)
Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
# removing unnecessary columns
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
# converting categorical columns into numbers
data = pd.get_dummies(data, drop_first=True)

data.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [8]:
# input data
X = data.drop("Exited", axis=1)

# output data
y = data["Exited"]

In [9]:
from sklearn.model_selection import train_test_split

# splitting dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.ensemble import RandomForestClassifier

# creating model
model = RandomForestClassifier()

# training model
model.fit(X_train, y_train)

RandomForestClassifier()

In [11]:
from sklearn.metrics import accuracy_score

# prediction
y_pred = model.predict(X_test)

# accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.867

In [12]:
# checking important columns
importance = pd.Series(model.feature_importances_, index=X.columns)

print(importance.sort_values(ascending=False).head(10))

Age                  0.237444
EstimatedSalary      0.148028
CreditScore          0.141708
Balance              0.139869
NumOfProducts        0.131548
Tenure               0.082072
IsActiveMember       0.042974
Geography_Germany    0.025736
HasCrCard            0.018495
Gender_Male          0.018339
dtype: float64